services:
  mysql:
    container_name: travel-mysql
    image: 'mysql:8'
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - '3306:3306'
    restart: always
    environment:
      - 'MYSQL_DATABASE=travel'
      - 'MYSQL_PASSWORD=travel!@#'
      - 'MYSQL_ROOT_PASSWORD=admin!@#'
      - 'MYSQL_USER=travel'
      - 'MYSQL_ROOT_HOST=%'
      - 'LANG: C.UTF-8'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
  nginx:
    container_name: travel-nginx
    image: nginx:stable-perl
    ports:
      - '80:80'
    volumes:
      - './ngnix/nginx.conf:/etc/nginx/nginx.conf'
    depends_on: [mysql, api]
  api:
    container_name: travel-api
    image: travel-api:latest
    ports:
      - '8080:8080'