services:
  s3mock:
    container_name: travel-s3
    image: adobe/s3mock:3.1.0
    environment:
      - 'initialBuckets=travel'
    ports:
      - '9090:9090'
  mysql:
    container_name: travel-mysql
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: always
    image: 'mysql:8'
    environment:
      - 'MYSQL_DATABASE=travel'
      - 'MYSQL_PASSWORD=travel!@#'
      - 'MYSQL_ROOT_PASSWORD=admin!@#'
      - 'MYSQL_USER=travel'
      - 'MYSQL_ROOT_HOST=%'
      - 'LANG: C.UTF-8'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    ports:
      - '3306:3306'