spring:
  docker:
    compose:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: none


  # real 환경 DB 정보
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password: