spring:
  profiles:
    active: local

  application:
    name: travel-server

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json