logging:
  level:
    web: debug

# JWT secret key
jwt:
  key: ffdfa414f1f47aa9091ac11e7bce5fb474921a3dfb03aba3d5546ccdcac88603
  expiration: 3600000
  issuer: travel-server-auth

spring:
  config:
    activate:
      on-profile: local

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  docker:
    compose:
      enabled: true
      file: docker-compose.yml

  jpa:
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: none

  sql:
    init:
      schema-locations:
      - classpath:sql/schema.sql
      - classpath:sql/schema-batch.sql
      mode: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel
    username: travel
    password: travel!@#


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: f357b75ff951c5b87948d01e2b7d14c2 #client-id
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: kakao
          naver:
            client-id: yEVi9MfbU1fNaO80_ci7
            client-secret: 7pyZokGXBa
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-name: naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

aws:
  s3:
    url: http://localhost:9090
    bucketName: travel
    region: us-east-1
    accessKey: foo
    secretKey: bar