
logging:
  level:
    web: info
    root: info
    io.everyone.travel: debug

spring:
  profiles:
    active: local

  application:
    name: travel-server

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect

  config:
    import:
      - classpath:/application-core-local.yml
      - classpath:/application-core-dev.yml
      - classpath:/application-core-prod.yml