logging:
  level:
    web: info
    root: info
    io.everyone.travel: debug

spring:
  profiles:
    active: local

  application:
    name: travel-server

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json